Repository jenkinsci/job-config-history-plugin, pull requests merged in 2021-12, with the labels that each got.

#133 Fix HTTP 404 for indentation.js
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/showDiffFiles.jelly
Labels: internal

#144 Align dependencies with core/pom
  pom.xml
Labels: dependencies

#148 chore: Rename plugin
  CHANGELOG.md
  README.md
  pom.xml
Labels: chore

#149 Update pom entries
  pom.xml
Labels: enhancement

#152 chore: Address dead methods
  src/main/java/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction.java
  src/main/java/hudson/plugins/jobConfigHistory/ComputerHistoryListener.java
  src/main/java/hudson/plugins/jobConfigHistory/ConfigInfo.java
  src/main/java/hudson/plugins/jobConfigHistory/ConfigInfoCollector.java
  src/main/java/hudson/plugins/jobConfigHistory/FileHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/GetDiffLines.java
  src/main/java/hudson/plugins/jobConfigHistory/HistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryActionFactory.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurger.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction.java
  src/main/java/hudson/plugins/jobConfigHistory/JobLocalConfiguration.java
  src/main/java/hudson/plugins/jobConfigHistory/LazyHistoryDescr.java
  src/main/java/hudson/plugins/jobConfigHistory/XmlSyntaxChecker.java
  src/test/java/hudson/plugins/jobConfigHistory/FileHistoryDaoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigBadgeActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurgerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootActionTest.java
Labels: chore

#153 Switch to a more incluse terminology, where applicable
  CHANGELOG.md
  src/main/java/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction.java
  src/main/java/hudson/plugins/jobConfigHistory/ComputerHistoryListener.java
  src/main/java/hudson/plugins/jobConfigHistory/FileHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryStrategy.java
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/showDiffFiles.jelly
  src/test/java/hudson/plugins/jobConfigHistory/ComputerHistoryListenerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/FileHistoryDaoTest.java
Labels: enhancement

#154 feat: Translate plugin to German
  .github/release-drafter.yml
  src/main/java/hudson/plugins/jobConfigHistory/ConfigInfoCollector.java
  src/main/java/hudson/plugins/jobConfigHistory/XmlSyntaxChecker.java
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/index_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/restoreQuestions_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/showDiffFiles_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigBadgeAction/badge.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/config.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/config_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/index_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/restoreQuestion_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/showDiffFiles_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/index_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/restoreQuestion_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/showDiffFiles_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobLocalConfiguration/config.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobLocalConfiguration/config_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/Messages.properties
  src/main/resources/hudson/plugins/jobConfigHistory/Messages_de.properties
  src/site/site.xml
Labels: feature

#157 Consistent indentation
  src/conf/checkstyle-ruleset.xml
  src/main/java/hudson/plugins/jobConfigHistory/FileHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistory.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurger.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction.java
  src/main/resources/hudson/plugins/jobConfigHistory/table.css
  src/main/resources/hudson/plugins/jobConfigHistory/xslt/sort.xslt
  src/main/webapp/css/diff_highlight.css
  src/main/webapp/css/style.css
  src/main/webapp/diff_highlight.css
  src/main/webapp/img/restore.svg
  src/test/java/hudson/plugins/jobConfigHistory/FileHistoryDaoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootActionTest.java
Labels: chore
