Repository jenkinsci/job-config-history-plugin, pull requests merged in 2022-04, with the labels that each got.

#187 [JENKINS-68025] `hudson.plugins.jobConfigHistory.FileHistoryDaoTest` fails on Java 17
  src/test/java/hudson/plugins/jobConfigHistory/FileHistoryDaoTest.java
Labels: tests

#190 build: Bump plugin to 4.40
  Jenkinsfile
  pom.xml
Labels: dependencies

#191 Added cloudbees-disk-usage-simple-plugin to the default ignore list
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryConsts.java
  src/main/webapp/help/help-excludePattern.html
Labels: enhancement
