Repository jenkinsci/job-config-history-plugin, pull requests merged in 2022-06, with the labels that each got.

#202 Improve styling of job history table
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/index.jelly
Labels: enhancement

#207 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#210 [JENKINS-68814] scope permission to ITEM and COMPUTER
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistory.java
Labels: feature
