Repository jenkinsci/job-config-history-plugin, pull requests merged in 2024-10, with the labels that each got.

#336 feat: update screenshots
  docs/img/Config_Overview_Page.png
  docs/img/Job_Config_History_Revision_Overview.png
  docs/img/Job_Diff_Side-By-Side_View.png
  docs/img/globalconfig.png
Labels: hacktoberfest-accepted

#338 [JENKINS-73883] Un-inline JavaScript in `history.jelly` and `index.jelly`
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/deleteRevisionAndTableEntry.js
  src/main/webapp/deleteRevisionAndTableEntry.js
Labels: internal

#340 Remove commons-net dependency from dependency management section
  pom.xml
Labels: skip-changelog

#341 Upgrade Mockito from 1.x to 5.x
  pom.xml
  src/test/java/hudson/plugins/jobConfigHistory/ConfigInfoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/FileHistoryDaoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigBadgeActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryJobListenerTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistorySaveableListenerTest.java
Labels: dependencies, java

#343 [JENKINS-74032][JENKINS-73033][JENKINS-73034] Improve CSP compatibility
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/show-diff-files-behaviour.js
Labels: internal
