Repository jenkinsci/job-config-history-plugin, pull requests merged in 2024-09, with the labels that each got.

#327 Set spotbugs threshold on medium and fixed findings
  pom.xml
  src/main/java/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction.java
  src/main/java/hudson/plugins/jobConfigHistory/ConfigInfoCollector.java
  src/main/java/hudson/plugins/jobConfigHistory/FileHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryBaseAction.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurger.java
  src/test/java/hudson/plugins/jobConfigHistory/ConfigInfoTest.java
Labels: internal, chore

#328 Replaced `StringUtils.trimToNull()` with JDK method
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistory.java
Labels: internal, chore

#329 Set Spotbugs to maximum effort and fixed issues
  pom.xml
  src/main/java/hudson/plugins/jobConfigHistory/ComputerHistoryListener.java
  src/main/java/hudson/plugins/jobConfigHistory/FileHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/FileNameComparator.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistory.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryActionFactory.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryBaseAction.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistorySaveableListener.java
  src/main/java/hudson/plugins/jobConfigHistory/JobLocalConfiguration.java
  src/main/java/hudson/plugins/jobConfigHistory/OverviewHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/ParsedDateComparator.java
  src/main/java/hudson/plugins/jobConfigHistory/PluginUtils.java
  src/main/java/hudson/plugins/jobConfigHistory/SideBySideView.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigBadgeActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistorySaveableListenerTest.java
Labels: internal, chore

#312 Allow developer control of parallel testing
  Jenkinsfile
  pom.xml
Labels: enhancement, internal

#330 Update README.md to display build result correctly
  README.md
Labels: documentation

#332 [JENKINS-70655] Re-Add missing diff button and restore its function
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history.jelly
Labels: bug

#333 fix: Restore paging and opening other pages in root config history
  src/main/resources/components/entries-per-page.jelly
  src/main/resources/components/pagination.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/index.jelly
Labels: bug
