Repository jenkinsci/job-config-history-plugin, pull requests merged in 2025-06, with the labels that each got.

#364 Migrate tests to JUnit5
  src/test/java/hudson/plugins/jobConfigHistory/AbstractHudsonTestCaseDeletingInstanceDir.java
  src/test/java/hudson/plugins/jobConfigHistory/ComputerConfigHistoryActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/ComputerHistoryListenerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/ConfigInfoCollectorTest.java
  src/test/java/hudson/plugins/jobConfigHistory/ConfigInfoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/jobConfigHistory/DeletedFileFilterTest.java
  src/test/java/hudson/plugins/jobConfigHistory/FileHistoryDaoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/FileNameComparatorTest.java
  src/test/java/hudson/plugins/jobConfigHistory/GetDiffLinesTest.java
  src/test/java/hudson/plugins/jobConfigHistory/HistoryDescrToConfigInfoTest.java
  src/test/java/hudson/plugins/jobConfigHistory/HistoryFileFilterTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigBadgeActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigBadgeActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryActionFactoryIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryBaseActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryBaseActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryJobListenerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryJobListenerTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurgerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurgerTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistorySaveableListenerTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryTest.java
  src/test/java/hudson/plugins/jobConfigHistory/LazyHistoryDescrTest.java
  src/test/java/hudson/plugins/jobConfigHistory/MimickedUserTest.java
  src/test/java/hudson/plugins/jobConfigHistory/NonDeletedFileFilterTest.java
  src/test/java/hudson/plugins/jobConfigHistory/NonJobsDirectoryFileFilterTest.java
  src/test/java/hudson/plugins/jobConfigHistory/ParsedDateComparatorTest.java
  src/test/java/hudson/plugins/jobConfigHistory/PluginIT.java
  src/test/java/hudson/plugins/jobConfigHistory/PluginUtilsTest.java
  src/test/java/hudson/plugins/jobConfigHistory/UnpackResourceZip.java
Labels: enhancement, internal

#371 update bom and adjust jenkins to 2.479.3
  pom.xml
Labels: dependencies

#372 UI overhaul
  pom.xml
  src/main/java/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction.java
  src/main/java/hudson/plugins/jobConfigHistory/FileHistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/HistoryDao.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction.java
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction.java
  src/main/resources/components/diff-body.jelly
  src/main/resources/components/diff-warning.jelly
  src/main/resources/components/diffNavigation.jelly
  src/main/resources/components/radio.jelly
  src/main/resources/components/restore-config-template.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/restoreQuestion_zh_TW.properties
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/restoreQuestions_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/ComputerConfigHistoryAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/restoreQuestion_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/restoreQuestion_zh_TW.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/history.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/index.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/restoreQuestion.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/restoreQuestion_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistoryRootAction/showDiffFiles.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/deleteRevisionAndTableEntry.js
  src/main/resources/hudson/plugins/jobConfigHistory/restore-config.css
  src/main/resources/hudson/plugins/jobConfigHistory/restore-config.js
  src/main/resources/hudson/plugins/jobConfigHistory/show-diff-files-behaviour.js
  src/main/resources/hudson/plugins/jobConfigHistory/table.css
  src/main/webapp/css/diff_highlight.css
  src/main/webapp/css/style.css
  src/main/webapp/diff_highlight.css
  src/main/webapp/highlight.js/styles/purebasic.css
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectActionTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootActionTest.java
Labels: bug, enhancement

#363 Add option to make change reason mandatory
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistory.java
  src/main/java/hudson/plugins/jobConfigHistory/JobLocalConfiguration.java
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/config.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/config_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/help-changeReasonCommentIsMandatory.html
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/help-changeReasonCommentIsMandatory_de.html
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigHistory/help-showChangeReasonCommentWindow.html
  src/main/resources/hudson/plugins/jobConfigHistory/JobLocalConfiguration/config.jelly
  src/main/resources/hudson/plugins/jobConfigHistory/JobLocalConfiguration/config_de.properties
  src/main/resources/hudson/plugins/jobConfigHistory/checkbox-logic.js
  src/main/resources/hudson/plugins/jobConfigHistory/mandatory-config-reason.js
  src/test/java/hudson/plugins/jobConfigHistory/ConfigurationAsCodeTest.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryJobChangeIT.java
  src/test/resources/hudson/plugins/jobConfigHistory/configuration-as-code-default-expected.yml
  src/test/resources/hudson/plugins/jobConfigHistory/configuration-as-code-expected.yml
  src/test/resources/hudson/plugins/jobConfigHistory/configuration-as-code.yml
Labels: enhancement, feature

#374 Fix and partially enable integration tests
  pom.xml
  src/main/java/hudson/plugins/jobConfigHistory/JobConfigBadgeAction.java
  src/main/resources/hudson/plugins/jobConfigHistory/JobConfigBadgeAction/badge.jelly
  src/test/java/hudson/plugins/jobConfigHistory/AbstractHudsonTestCaseDeletingInstanceDir.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigBadgeActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryBaseActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryJobChangeIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryJobListenerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryProjectActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryPurgerIT.java
  src/test/java/hudson/plugins/jobConfigHistory/JobConfigHistoryRootActionIT.java
  src/test/java/hudson/plugins/jobConfigHistory/PluginIT.java
  src/test/java/hudson/plugins/jobConfigHistory/TestHelper.java
Labels: internal, tests

#377 Parallelize integration tests
  pom.xml
Labels: internal, tests
